apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cis-ops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Sayan8967/cis-ops-app
    targetRevision: releaseV2
    path: k8s/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: cis-ops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
