# ==============================================
# CIS Operations Dashboard - Complete Manifest
# Generated: 2025-07-30 22:15:48 UTC
# Commit: 604dda6fea2fb387676975cdd8fae54efdb40f30
# ==============================================

---
apiVersion: v1
kind: Namespace
metadata:
  name: cis-ops

---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx

---
# NGINX Ingress Controller Service
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  type: LoadBalancer    # or NodePort for bare-metal
  selector:
    app.kubernetes.io/name: ingress-nginx
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https

---
# NGINX Ingress Controller Deployment (fixed)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ingress-controller
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/version: "1.8.2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/part-of: ingress-nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ingress-nginx
        app.kubernetes.io/part-of: ingress-nginx
      annotations:
        prometheus.io/scrape: "true"
    spec:
      # hostNetwork & nodeSelector removed so pods can schedule anywhere
      serviceAccountName: nginx-ingress-serviceaccount
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Equal
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Equal
      containers:
        - name: controller
          image: registry.k8s.io/ingress-nginx/controller:v1.8.2@sha256:74834d3d25b336b62cabeb8bf7f1d788706e2cf1cfd64022de4137ade8881ff2
          args:
            - /nginx-ingress-controller
            - --configmap=ingress-nginx/nginx-configuration
            - --publish-service=ingress-nginx/ingress-nginx
            - --annotations-prefix=nginx.ingress.kubernetes.io
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 10254
          readinessProbe:
            httpGet:
              path: /healthz
              port: 10254

---
# IngressClass
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: nginx
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  controller: k8s.io/ingress-nginx

# … rest of your Namespace, ConfigMaps, RBAC, Deployments, Services, Ingress …
