apiVersion: v1
kind: Service
metadata:
  name: cis-ops-backend-service
  namespace: cis-ops
  labels:
    app: cis-ops-backend
spec:
  type: NodePort
  selector:
    app: cis-ops-backend
  ports:
  - port: 4000
    targetPort: 4000
    nodePort: 30400
    name: http
  - port: 9400
    targetPort: 9400
    name: metrics
