apiVersion: apps/v1
kind: Deployment
metadata:
  name: cis-ops-backend
  namespace: cis-ops
  labels:
    app: cis-ops-backend
    app.kubernetes.io/name: cis-ops
    app.kubernetes.io/component: backend
    app.kubernetes.io/version: aa44530ab6f5fec04e0570feb901474c0f71fd03
    app.kubernetes.io/managed-by: argocd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cis-ops-backend
  template:
    metadata:
      labels:
        app: cis-ops-backend
        app.kubernetes.io/name: cis-ops
        app.kubernetes.io/component: backend
        app.kubernetes.io/version: aa44530ab6f5fec04e0570feb901474c0f71fd03
    spec:
      containers:
      - name: backend
        image: docker.io/sayan896/cis-ops-backend:aa44530ab6f5fec04e0570feb901474c0f71fd03
        ports:
        - containerPort: 4000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "4000"
        - name: CORS_ORIGIN
          value: "*"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 4000
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 4000
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3
