apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: cis-ops
data:
  fluent-bit.conf: |-
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info
        Parsers_File parsers.conf

    [INPUT]
        Name        tail
        Path        /var/log/containers/*.log
        Parser      docker
        Tag         kube.*
        Mem_Buf_Limit 5MB

    [FILTER]
        Name        kubernetes
        Match       kube.*
        Kube_URL    https://kubernetes.default.svc:443
        Kube_Tag_Prefix kube.var.log.containers.

    [OUTPUT]
        Name        http
        Match       *
        Host        ${LOKI_HOST}
        Port        ${LOKI_PORT}
        URI         /loki/api/v1/push
        Format      json
        Header      Content-Type application/json

  parsers.conf: |-
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L

  # Note: replace ${LOKI_HOST}/${LOKI_PORT} with your Loki endpoint via env in the DaemonSet or edit this ConfigMap


