apiVersion: apps/v1
kind: Deployment
metadata:
  name: cis-ops-frontend
  namespace: cis-ops
  labels:
    app: cis-ops-frontend
    app.kubernetes.io/name: cis-ops
    app.kubernetes.io/component: frontend
    app.kubernetes.io/managed-by: argocd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cis-ops-frontend
  template:
    metadata:
      labels:
        app: cis-ops-frontend
        app.kubernetes.io/name: cis-ops
        app.kubernetes.io/component: frontend
    spec:
      containers:
      - name: frontend
        image: docker.io/sayan896/cis-ops-frontend:4999ba291ccd1370b2d6025a3ffb4f49e32da5fb
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
