apiVersion: apps/v1
kind: Deployment
metadata:
  name: cis-ops-frontend
  namespace: cis-ops
  labels:
    app: cis-ops-frontend
    app.kubernetes.io/name: cis-ops
    app.kubernetes.io/component: frontend
    app.kubernetes.io/version: 684bcba66a9d8c6befb96a207359b02224377d44
    app.kubernetes.io/managed-by: argocd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cis-ops-frontend
  template:
    metadata:
      labels:
        app: cis-ops-frontend
        app.kubernetes.io/name: cis-ops
        app.kubernetes.io/component: frontend
        app.kubernetes.io/version: 684bcba66a9d8c6befb96a207359b02224377d44
    spec:
      containers:
      - name: frontend
        image: docker.io/sayan896/cis-ops-frontend:684bcba66a9d8c6befb96a207359b02224377d44
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
          successThreshold: 1
