apiVersion: v1
kind: Service
metadata:
  name: cis-ops-frontend-service
  namespace: cis-ops
  labels:
    app: cis-ops-frontend
spec:
  type: NodePort
  selector:
    app: cis-ops-frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
