apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cis-ops-metrics-reader
  labels:
    app.kubernetes.io/name: cis-ops
rules:
- apiGroups: [""]
  resources: 
    - "nodes"
    - "pods"
    - "services"
    - "namespaces"
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources:
    - "deployments"
    - "replicasets"
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources:
    - "nodes"
    - "pods"
  verbs: ["get", "list"]
