apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
  namespace: cis-ops
  labels:
    app: postgres-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      labels:
        app: postgres-exporter
    spec:
      containers:
      - name: postgres-exporter
        image: prometheuscommunity/postgres-exporter:latest
        args:
          # Bind exporter to localhost on a non-standard port so nginx sidecar can terminate TLS
          - "--web.listen-address=127.0.0.1:9188"
        ports:
        - containerPort: 9188
          name: metrics-internal
        env:
        - name: DATA_SOURCE_NAME
          valueFrom:
            secretKeyRef:
              name: pg-exporter-dsn
              key: DATA_SOURCE_NAME
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
      - name: nginx-tls
        image: nginx:alpine
        ports:
        - containerPort: 9187
          name: metrics
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: nginx-certs
          mountPath: /etc/nginx/certs
          readOnly: true
        resources:
          requests:
            cpu: 50m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 64Mi
      volumes:
      - name: nginx-config
        configMap:
          name: pg-exporter-nginx-cm
      - name: nginx-certs
        secret:
          secretName: pg-exporter-tls


