apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-postgres-scrape
  namespace: cis-ops
data:
  scrape_configs.yaml: |-
    - job_name: 'postgres_exporter'
      metrics_path: /metrics
      static_configs:
        - targets: ['postgres-exporter.cis-ops.svc.cluster.local:9187']


