apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-backend-scrape
  namespace: cis-ops
data:
  scrape_configs.yaml: |-
    - job_name: 'cis-ops-backend'
      metrics_path: /metrics
      static_configs:
        - targets: ['<BACKEND_HOST>:4000']

