apiVersion: v1
kind: ConfigMap
metadata:
  name: smoke-test-script
  namespace: cis-ops
data:
  smoke-test.sh: |-
    #!/bin/sh
    set -eu

    echo "[smoke-test] Starting smoke tests..."
    FAILS=0

    BACKEND_URL="http://cis-ops-backend-service.cis-ops.svc.cluster.local:9400/metrics"
    echo "[smoke-test] Checking backend metrics at $BACKEND_URL"
    if curl -sS --max-time 10 "$BACKEND_URL" | grep -q "cis_ops_http_request_duration_ms\|process_cpu_seconds_total"; then
      echo "[smoke-test] OK: backend metrics present"
    else
      echo "[smoke-test] WARN: backend metrics not present or request failed"
      FAILS=$((FAILS+1))
    fi

    PG_URL="http://postgres-exporter.cis-ops.svc.cluster.local:9187/metrics"
    echo "[smoke-test] Checking Postgres exporter at $PG_URL"
    if curl -sS --max-time 10 "$PG_URL" | grep -q "pg_up\|postgres_exporter\|pg_stat"; then
      echo "[smoke-test] OK: postgres exporter metrics present"
    else
      echo "[smoke-test] WARN: postgres exporter metrics not present or request failed"
      FAILS=$((FAILS+1))
    fi

    echo "[smoke-test] Checking Fluent Bit pods"
    # check pod existence via kubectl
    if kubectl get pods -n cis-ops -l name=fluent-bit --no-headers 2>/dev/null | awk '{print $1}' | grep -q .; then
      echo "[smoke-test] OK: fluent-bit pods found"
      POD=$(kubectl get pods -n cis-ops -l name=fluent-bit -o jsonpath='{.items[0].metadata.name}')
      echo "[smoke-test] Inspecting logs of $POD (last 50 lines)"
      kubectl logs -n cis-ops "$POD" --tail=50 || true
    else
      echo "[smoke-test] WARN: fluent-bit pods not found"
      FAILS=$((FAILS+1))
    fi

    echo "[smoke-test] Summary: $FAILS checks failed"
    if [ "$FAILS" -gt 0 ]; then
      echo "[smoke-test] Completed with warnings — this will NOT fail the ArgoCD sync. Review logs above."
    else
      echo "[smoke-test] All checks passed"
    fi

    # Always exit 0 so ArgoCD sync is not blocked by smoke-test failures
    exit 0


