apiVersion: apps/v1
kind: Deployment
metadata:
  name: cis-ops-backend
  namespace: cis-ops
  labels:
    app: cis-ops-backend
    version: 9a87a00b5f6dd9084a4e4a68e360c35ae446ff42
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cis-ops-backend
  template:
    metadata:
      labels:
        app: cis-ops-backend
        version: 9a87a00b5f6dd9084a4e4a68e360c35ae446ff42
    spec:
      containers:
      - name: backend
        image: docker.io/sayan896/cis-ops-backend:9a87a00b5f6dd9084a4e4a68e360c35ae446ff42
        ports:
        - containerPort: 4000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "4000"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/metrics
            port: 4000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/metrics
            port: 4000
          initialDelaySeconds: 5
          periodSeconds: 5
