apiVersion: apps/v1
kind: Deployment
metadata:
  name: cis-ops-frontend
  namespace: cis-ops
  labels:
    app: cis-ops-frontend
    version: 9a87a00b5f6dd9084a4e4a68e360c35ae446ff42
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cis-ops-frontend
  template:
    metadata:
      labels:
        app: cis-ops-frontend
        version: 9a87a00b5f6dd9084a4e4a68e360c35ae446ff42
    spec:
      containers:
      - name: frontend
        image: docker.io/sayan896/cis-ops-frontend:9a87a00b5f6dd9084a4e4a68e360c35ae446ff42
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
