apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cis-ops

resources:
- namespace.yaml
- nginx-ingress-controller.yaml
- ingress-class.yaml
- backend-deployment.yaml
- frontend-deployment.yaml
- backend-service.yaml
- frontend-service.yaml
- ingress.yaml
- pre-sync-hook.yaml

images:
- name: docker.io/sayan896/cis-ops-backend
  newTag: 465e746a467527b477a5192b023afec1f01155b0
- name: docker.io/sayan896/cis-ops-frontend
  newTag: 465e746a467527b477a5192b023afec1f01155b0

commonLabels:
  app.kubernetes.io/name: cis-ops
  app.kubernetes.io/version: 465e746a467527b477a5192b023afec1f01155b0
  app.kubernetes.io/managed-by: argocd

# Patches for production-specific configurations
patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: cis-ops-backend
  spec:
    template:
      spec:
        containers:
        - name: backend
          env:
          - name: CORS_ORIGIN
            value: "*"
