apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cis-ops

resources:
- namespace.yaml
- backend-deployment.yaml
- frontend-deployment.yaml
- backend-service.yaml
- frontend-service.yaml
- ingress.yaml

images:
- name: docker.io/sayan896/cis-ops-backend
  newTag: 3cecb00a2eff458372bad4710f56ac456dcc0956
- name: docker.io/sayan896/cis-ops-frontend
  newTag: 3cecb00a2eff458372bad4710f56ac456dcc0956

commonLabels:
  app.kubernetes.io/name: cis-ops
  app.kubernetes.io/version: 3cecb00a2eff458372bad4710f56ac456dcc0956
  app.kubernetes.io/managed-by: argocd
