apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cis-ops

resources:
- namespace.yaml
- nginx-ingress-controller.yaml
- ingress-class.yaml
- backend-deployment.yaml
- frontend-deployment.yaml
- backend-service.yaml
- frontend-service.yaml
- ingress.yaml
- pre-sync-hook.yaml

images:
- name: docker.io/sayan896/cis-ops-backend
  newTag: acd94208304ba0beef2fba79fb198af3ec363bda
- name: docker.io/sayan896/cis-ops-frontend
  newTag: acd94208304ba0beef2fba79fb198af3ec363bda

labels:
  app.kubernetes.io/name: cis-ops
  app.kubernetes.io/version: acd94208304ba0beef2fba79fb198af3ec363bda
  app.kubernetes.io/managed-by: argocd

# Patches for production-specific configurations
patches:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: cis-ops-backend
  spec:
    template:
      spec:
        containers:
        - name: backend
          env:
          - name: CORS_ORIGIN
            value: "*"
