# NGINX Ingress Controller Installation
# Apply this first: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/cloud/deploy.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-tcp-microk8s-conf
  namespace: ingress-nginx
data:
  "4000": "cis-ops/cis-ops-backend-service:4000"
